"""add nik, name, phone_number

Revision ID: aaf1c1eaca54
Revises: 31ba0e4860be
Create Date: 2023-12-10 05:39:26.159773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf1c1eaca54'
down_revision = '31ba0e4860be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nik', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=14), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('name')
        batch_op.drop_column('nik')

    # ### end Alembic commands ###
