"""nik not optional

Revision ID: b1aec2781cdc
Revises: aaf1c1eaca54
Create Date: 2023-12-10 06:05:00.721245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1aec2781cdc'
down_revision = 'aaf1c1eaca54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('nik',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('nik',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###
